export const Users = [
  { id: 1, username: "Vamsi Naidu", userImage: "/assets/images/p1.jpg" },
  { id: 2, username: "Ramesh Nayak", userImage: "/assets/images/p2.jpg" },
  { id: 3, username: "Padmavathi Konneru", userImage: "/assets/images/p3.jpg" },
  { id: 4, username: "Anjali Nikki", userImage: "/assets/images/p4.jpg" },
  { id: 5, username: "Kolli Karthik", userImage: "/assets/images/p5.jpg" },
  { id: 6, username: "Anil Ravuri", userImage: "/assets/images/p6.jpg" },
  { id: 7, username: "Kavitha Kolli", userImage: "/assets/images/p12.jpg" },
  { id: 8, username: "Anitha", userImage: "/assets/images/p7.jpg" },
  { id: 9, username: "Jinni Jennifer", userImage: "/assets/images/p8.jpg" },
  { id: 10, username: "Hemanth Katturu", userImage: "/assets/images/p9.jpg" },
  {
    id: 11,
    username: "Kishore Kancherla",
    userImage: "/assets/images/p10.jpg",
  },
  { id: 12, username: "Raja Ram", userImage: "/assets/images/p11.jpg" },
];

export const PostsData = [
  {
    id: 1,
    userId: 1,
    image: "/assets/images/p1.jpg",
    desc: "This is my first Post(:-----",
    date: "just now",
    likes: 10,
    comments: 3,
  },
  {
    id: 2,
    userId: 2,
    image: "/assets/images/p12.jpg",
    desc: "I Love the nature more than U (:--:)",
    date: "5min ago",
    likes: 50,
    comments: 20,
  },
  {
    id: 3,
    userId: 3,
    image: "/assets/images/p3.jpg",
    desc: "I Like My Self",
    date: "1day ago",
    likes: 32,
    comments: 12,
  },
  {
    id: 4,
    userId: 4,
    image: "/assets/images/p4.jpg",
    desc: "Find who am I",
    date: "2days ago",
    likes: 100,
    comments: 43,
  },
  {
    id: 5,
    userId: 5,
    image: "/assets/images/p10.jpg",
    desc: "My Celebrations",
    date: "3days ago",
    likes: 200,
    comments: 50,
  },
  {
    id: 6,
    userId: 6,
    image: "/assets/images/p11.jpg",
    desc: "My Lover Favourite Place",
    date: "1week ago",
    likes: 150,
    comments: 23,
  },
  {
    id: 7,
    userId: 7,
    image: "/assets/images/p12.jpg",
    desc: "Life is Beautifull",
    date: "1month ago",
    likes: 39,
    comments: 34,
  },
  {
    id: 8,
    userId: 8,
    image: "/assets/images/p13.jpg",
    desc: "Kings desrve the royal Life",
    date: "10months ago",
    likes: 29,
    comments: 60,
  },
  {
    id: 9,
    userId: 9,
    image: "/assets/images/p14.jpg",
    desc: "family celebration at this ......-)",
    date: "1year ago",
    likes: 33,
    comments: 2,
  },
  {
    id: 10,
    userId: 10,
    image: "/assets/images/p15.jpg",
    desc: "Please Don't Love",
    date: "14months ago",
    likes: 999,
    comments: 1000,
  },
  {
    id: 11,
    userId: 11,
    image: "/assets/images/p16.jpg",
    desc: "Never mind peoples Nonsense",
    date: "2years ago",
    likes: 1000,
    comments: 1000,
  },
  {
    id: 12,
    userId: 12,
    image: "/assets/images/p17.jpg",
    desc: "Never mind peoples Nonsense",
    date: "2years ago",
    likes: 1000,
    comments: 1000,
  },
];
